eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:7861/eureka/

server:
    port: 8765

spring:
    application:
        name: service-consumer-feign

feign:
  hystrix:
    enabled: true